// Master foe-icon vocabulary: every word the GM may pick in an
// [[enemy: ... | icon: WORD]] directive maps to a game-icons.net icon
// (react-icons/gi, CC BY 3.0). scenarios.py lists 50 of these per story —
// keep the two files in sync (test_server.py checks it).
import {
  // fantasy & monsters
  GiRat, GiGoblinHead, GiOrcHead, GiSkeleton, GiShamblingZombie, GiGhost,
  GiSpectre, GiWolfHead, GiBearHead, GiSpiderFace, GiSnake, GiDragonHead,
  GiWyvern, GiTroll, GiOgre, GiMinotaur, GiVampireDracula, GiWitchFlight,
  GiDevilMask, GiSlime, GiMimicChest, GiRockGolem, GiGargoyle, GiHarpy,
  GiGiantSquid, GiSharkJaws, GiCrocJaws, GiScorpion, GiBat, GiRaven,
  GiBoarTusks, GiLion, GiGriffinSymbol, GiCyclops, GiCultist, GiBandit,
  GiHoodedAssassin, GiHoodedFigure, GiBlackKnightHelm, GiGuards,
  GiExecutionerHood, GiPirateCaptain, GiBarbarian, GiBowman, GiWizardFace,
  GiJesterHat, GiCrownedSkull, GiMummyHead, GiWerewolf, GiGrimReaper,
  GiImpLaugh, GiCrossedSwords, GiWhip, GiMonsterGrasp,
  // people & modern life
  GiTeacher, GiWhistle, GiBullyMinion, GiBrassKnuckles, GiBoxingGlove,
  GiBiceps, GiQueenCrown, GiMegaphone, GiChessKnight, GiGamepad, GiLaptop,
  GiBookCover, GiGraduateCap, GiMedal, GiSoccerBall, GiBasketballBall,
  GiTrophyCup, GiGuitar, GiDrum, GiMicrophone, GiPaintBrush, GiDramaMasks,
  GiTestTubes, GiChefToque, GiSyringe, GiBroom, GiBookshelf, GiPhotoCamera,
  GiCctvCamera, GiRobotGolem, GiDeliveryDrone, GiPoliceBadge, GiSpyglass,
  GiNewspaper, GiTopHat, GiBowTie, GiHighHeel, GiSunglasses, GiBeard,
  // office
  GiTie, GiBriefcase, GiFiles, GiScales, GiCalculator, GiMoneyStack,
  GiContract, GiGavel, GiPieChart, GiEnvelope, GiPhone, GiSmartphone,
  GiPaperClip, GiStapler, GiCoffeeCup, GiOfficeChair, GiElevator,
  GiVendingMachine, GiKey, GiDoorHandle, GiHandcuffs, GiNotebook,
  GiArchiveResearch, GiPapers,
  // time, pressure, feelings
  GiAlarmClock, GiHourglass, GiBrokenHeart, GiHearts, GiCandleFlame,
  GiTimeBomb, GiTimeTrap, GiBackwardTime, GiPocketWatch, GiBrain,
  GiMirrorMirror, GiCrystalBall, GiCardRandom, GiCardPick, GiYinYang,
  GiMeditation, GiInnerSelf, GiDuality, GiOldKing, GiFamilyTree,
  GiFilmStrip, GiVideoCamera, GiScrollUnfurled, GiQuillInk, GiTombstone,
  GiCoffin, GiPuppet, GiSecretBook, GiSpellBook,
  // animals & travel
  GiSittingDog, GiDogHouse, GiCat, GiOwl, GiSeagull, GiEagleHead, GiBee,
  GiWaspSting, GiAnt, GiFly, GiSpiderWeb, GiFrog, GiTurtle, GiOctopus,
  GiCrab, GiGecko, GiMonkey, GiGorilla, GiPanda, GiKoala, GiTigerHead,
  GiElephant, GiCamelHead, GiBull, GiGoat, GiRam, GiHorseHead, GiDonkey,
  GiPig, GiChicken, GiRooster, GiSheep, GiJellyfish,
  GiPassport, GiSnatch, GiCityCar, GiScooter, GiSteamLocomotive, GiRailway,
  GiAirplane, GiTicket, GiSuitcase, GiSchoolBag, GiWorld, GiCompass,
  GiTreasureMap, GiCampingTent, GiCampfire, GiMountainClimbing, GiVolcano,
  GiDesert, GiPalmTree, GiBigWave, GiSurfBoard, GiThermometerHot, GiIceCube,
  GiLightningStorm, GiNoodles, GiPizzaSlice, GiChopsticks,
} from "react-icons/gi";

export const FOE_ICON_MAP = {
  // fantasy & monsters
  rat: GiRat, goblin: GiGoblinHead, orc: GiOrcHead, skeleton: GiSkeleton,
  zombie: GiShamblingZombie, ghost: GiGhost, wraith: GiSpectre,
  wolf: GiWolfHead, bear: GiBearHead, spider: GiSpiderFace, snake: GiSnake,
  dragon: GiDragonHead, wyvern: GiWyvern, troll: GiTroll, ogre: GiOgre,
  minotaur: GiMinotaur, vampire: GiVampireDracula, witch: GiWitchFlight,
  demon: GiDevilMask, slime: GiSlime, mimic: GiMimicChest,
  golem: GiRockGolem, gargoyle: GiGargoyle, harpy: GiHarpy,
  kraken: GiGiantSquid, shark: GiSharkJaws, crocodile: GiCrocJaws,
  scorpion: GiScorpion, bat: GiBat, raven: GiRaven, boar: GiBoarTusks,
  lion: GiLion, griffin: GiGriffinSymbol, cyclops: GiCyclops,
  cultist: GiCultist, bandit: GiBandit, assassin: GiHoodedAssassin,
  stranger: GiHoodedFigure, knight: GiBlackKnightHelm, guard: GiGuards,
  executioner: GiExecutionerHood, pirate: GiPirateCaptain,
  barbarian: GiBarbarian, archer: GiBowman, wizard: GiWizardFace,
  jester: GiJesterHat, lich: GiCrownedSkull, mummy: GiMummyHead,
  werewolf: GiWerewolf, reaper: GiGrimReaper, imp: GiImpLaugh,
  duel: GiCrossedSwords, taskmaster: GiWhip, monster: GiMonsterGrasp,
  // people & modern life
  teacher: GiTeacher, coach: GiWhistle, bully: GiBullyMinion,
  delinquent: GiBrassKnuckles, boxer: GiBoxingGlove, jock: GiBiceps,
  "queen-bee": GiQueenCrown, gossip: GiMegaphone, chess: GiChessKnight,
  gamer: GiGamepad, hacker: GiLaptop, bookworm: GiBookCover,
  senior: GiGraduateCap, prefect: GiMedal, striker: GiSoccerBall,
  baller: GiBasketballBall, champion: GiTrophyCup, guitarist: GiGuitar,
  drummer: GiDrum, singer: GiMicrophone, artist: GiPaintBrush,
  actor: GiDramaMasks, scientist: GiTestTubes, chef: GiChefToque,
  nurse: GiSyringe, janitor: GiBroom, librarian: GiBookshelf,
  photographer: GiPhotoCamera, security: GiCctvCamera, robot: GiRobotGolem,
  drone: GiDeliveryDrone, police: GiPoliceBadge, detective: GiSpyglass,
  journalist: GiNewspaper, tycoon: GiTopHat, charmer: GiBowTie,
  diva: GiHighHeel, "cool-kid": GiSunglasses, elder: GiBeard,
  // office
  boss: GiTie, manager: GiBriefcase, hr: GiFiles, lawyer: GiScales,
  auditor: GiCalculator, "money-man": GiMoneyStack, contract: GiContract,
  judge: GiGavel, meeting: GiPieChart, email: GiEnvelope, caller: GiPhone,
  "phone-addict": GiSmartphone, bureaucrat: GiPaperClip, admin: GiStapler,
  "coffee-fiend": GiCoffeeCup, "chair-warmer": GiOfficeChair,
  elevator: GiElevator, "vending-machine": GiVendingMachine,
  gatekeeper: GiKey, "locked-door": GiDoorHandle, handcuffs: GiHandcuffs,
  intern: GiNotebook, archivist: GiArchiveResearch, paperwork: GiPapers,
  // time, pressure, feelings
  exam: GiAlarmClock, deadline: GiHourglass, heartbreak: GiBrokenHeart,
  crush: GiHearts, burnout: GiCandleFlame, "ticking-bomb": GiTimeBomb,
  "time-trap": GiTimeTrap, rewind: GiBackwardTime, "pocket-watch": GiPocketWatch,
  memory: GiBrain, mirror: GiMirrorMirror, fortune: GiCrystalBall,
  gambler: GiCardRandom, "card-sharp": GiCardPick, balance: GiYinYang,
  guru: GiMeditation, "inner-self": GiInnerSelf, "double-life": GiDuality,
  patriarch: GiOldKing, family: GiFamilyTree, "old-film": GiFilmStrip,
  vlogger: GiVideoCamera, prophecy: GiScrollUnfurled, poet: GiQuillInk,
  grave: GiTombstone, coffin: GiCoffin, puppet: GiPuppet,
  "secret-book": GiSecretBook, spellbook: GiSpellBook,
  // animals & travel
  dog: GiSittingDog, "guard-dog": GiDogHouse, cat: GiCat, owl: GiOwl,
  seagull: GiSeagull, eagle: GiEagleHead, bee: GiBee, wasp: GiWaspSting,
  ant: GiAnt, fly: GiFly, "spider-web": GiSpiderWeb, frog: GiFrog,
  turtle: GiTurtle, octopus: GiOctopus, crab: GiCrab, gecko: GiGecko,
  monkey: GiMonkey, gorilla: GiGorilla, panda: GiPanda, koala: GiKoala,
  tiger: GiTigerHead, elephant: GiElephant, camel: GiCamelHead,
  bull: GiBull, goat: GiGoat, ram: GiRam, horse: GiHorseHead,
  donkey: GiDonkey, pig: GiPig, chicken: GiChicken, rooster: GiRooster,
  sheep: GiSheep, jellyfish: GiJellyfish,
  customs: GiPassport, pickpocket: GiSnatch, taxi: GiCityCar,
  scooter: GiScooter, train: GiSteamLocomotive, railway: GiRailway,
  airplane: GiAirplane, "ticket-tout": GiTicket, "lost-luggage": GiSuitcase,
  backpacker: GiSchoolBag, globetrotter: GiWorld, wayfinder: GiCompass,
  "treasure-map": GiTreasureMap, camper: GiCampingTent, campfire: GiCampfire,
  mountaineer: GiMountainClimbing, volcano: GiVolcano, desert: GiDesert,
  islander: GiPalmTree, wave: GiBigWave, surfer: GiSurfBoard,
  heatwave: GiThermometerHot, blizzard: GiIceCube, storm: GiLightningStorm,
  "noodle-vendor": GiNoodles, "pizza-guy": GiPizzaSlice,
  "street-cook": GiChopsticks,
};
